= Semantic Release für gradle Projekte

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

Bereits 1997 hat Eric S. Raymond in seinem Essay "link:https://de.wikipedia.org/wiki/Die_Kathedrale_und_der_Basar[Die Kathedrale und der Basar]"
den Leitsatz "Release early, release often" geprägt. Mit dem DevOps-Paradigma ist das Continuous Delivery Konzept,
das eben diesem Leitsatz folgt, aktueller den je. In der aktuellen Software-Entwicklung geht es also auch darum, Releases
reibungslos erstellen zu können. Damit dies funktioniert, muss der Erstellungs-Prozess für ein Release einfach,
reproduzierbar und automatisiert sein.

Um Releases ein-eindeutig identifizeren und referenzieren zu können, wird eine Namensgebung für Versionen benötigt. Dazu
hat sich das link:https://semver.org/[Semantic Versioning] durchgesetzt. Mit der Verwendung von
link:https://www.conventionalcommits.org/[Conventional Commits] können Entwickler mit einfachen Commit-Messages
angeben, welcher Teil einer Version inkrementiert werden soll. Dies bietet den Vorteil, das Änderungen am Code
direkt dokumentiert werden und in dem Changelog eines Projektes dann automatisch aufgelistet werden können. Die Spezifikation
enthält Vorgaben, wie die Commit-Messages angelegt werden müssen. Einige Schlüssel-Begriffe darin sind:

* fix
* feat
* BREAKING CHANGE

Mit diesen Prefixes in den Commit Messages wird entschieden, welcher Teil einer Versionsnummer inkrementiert wird.
Somit können dann Builds automatisch gestartet und mit der daraus gewonnenen Versionnummer publiziert werden.

Um den Release Prozess mit den vorgenannten Spezifikationen zu automatisieren, gibt es im Javascript-Bereich das
link:https://semantic-release.gitbook.io/semantic-release/[Semantic Release] Toolset. Dieses Toolset ist zwar für Javascript
gebaut und optimiert, kann jedoch auch in anderen Umgebungen eingesetzt werden. In diesem Artikel möchte ich auf die
Verwendung in einem Java-Projekt, das mit Gradle gebaut wird, eingehen.

In gradle wird für das Publizieren von Artefakten das link:https://docs.gradle.org/current/userguide/publishing_ivy.html[Ivy Publish Plugin]
oder das link:https://docs.gradle.org/current/userguide/publishing_maven.html[Maven Publish Plugin] verwenden. Im Prinzip
arbeiten beide Plugins ähnlich und unterscheiden sich vor allem in den verwendeten Metadaten der Repositories. Im folgenden
wird das Maven Plugin verwendet, da diese Repositories häufig anzutreffen sind.

Für eine ein-eindeutige Identifikation der Artefakte werden in gradle die folgenden Properties benötigt:

* groupId
* artefactId
* version

Die Version wird hier von dem Semantic Release Toolset generiert und über die Kommandozeile an gradle übergeben. Um dies
zu ermöglichen, muss die Version in den gradle.properties definiert werden und nicht in der build.gradle.

Das Semantic Release Toolset verwendet die Datei .releaserc (andere Dateien bzw. Formate können link:https://semantic-release.gitbook.io/semantic-release/usage/configuration[hier]
eingesehen werden) um den Prozess zu steuern. Beispielhaft kann das dann wie folgt aussehen:

[source,json]
----
{
    "branches": ["master"],
    "plugins": [
        "@semantic-release/commit-analyzer",
        "@semantic-release/release-notes-generator",
        ["@semantic-release/github", {
            "assets": [
                {"path": "../../build/distributions/project.tar", "label": "Binary - Tar"},
                {"path": "../../build/distributions/project.zip", "label": "Binary - Zip"}
            ]
        }],
        ["@semantic-release/exec", {
          "prepareCmd" : "./release-files.sh ${nextRelease.version}"
        }]
    ]
}
----



