name: CI Build

on: [push]

jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Compile
      run: ./gradlew clean compileJava compileTestJava

#  tests:
#    name: Tests
#    needs: compile
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v2
#      - name: Set up JDK 11
#        uses: actions/setup-java@v1
#        with:
#          java-version: 11
#      - name: Grant execute permission for gradlew
#        run: chmod +x gradlew
#      - name: Run Tests
#        run: ./gradlew clean test detekt jacocoTestReport
#      - name: Upload test results
#        uses: actions/upload-artifact@v1
#        with:
#          name: reports
#          path: build/reports
#
#  sonarqube:
#    name: SonarQube Check
#    needs: tests
#    runs-on: ubuntu-latest
#
#    steps:
#    - uses: actions/checkout@v2
#      with:
#        fetch-depth: 0
#    - name: Set up JDK 11
#      uses: actions/setup-java@v1
#      with:
#        java-version: 11
#    - name: Grant execute permission for gradlew
#      run: chmod +x gradlew
#    - name: Download test results
#      uses: actions/download-artifact@v1
#      with:
#        name: reports
#        path: build/reports
#    - name: Sonarqube Check
#      run: ./gradlew sonarqube -x test -x detekt
#      env:
#        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#
#  security:
#    name: Security Checks
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v2
#        with:
#          fetch-depth: 0
#      - name: Set up JDK 11
#        uses: actions/setup-java@v1
#        with:
#          java-version: 11
#      - name: Grant execute permission for gradlew
#        run: chmod +x gradlew
#      - name: Check OWASP
#        run: ./gradlew dependencyCheckAnalyze

  release:
    name: Release
#    needs: [sonarqube, security]
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build package
        run: ./gradlew assemble -x test
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 13
      - name: Add plugin for conventional commits
        run: npm install conventional-changelog-conventionalcommits @semantic-release/exec
        working-directory: ./.github/workflows
      - name: Release to GitHub
        working-directory: ./.github/workflows
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          revnumber: $revnumber
        run: |
          npx semantic-release
          echo 'REV: $revnumber'

  publish-docs:
    name: Publish Docs
    needs: release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build package
        run: |
          echo "ENV: $revnumber"
          ./gradlew asciidoctor
      - name: Publish documentation
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build/docs
          CLEAN: true
