name: Push - CI with Gradle

on:
  push:
    branches-ignore:
      - master

jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Compile
      run: ./gradlew clean compileJava compileTestJava

  tests:
    name: Tests
    needs: compile
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run Tests
        run: ./gradlew clean test detekt jacocoTestReport
      - name: Upload test results
        uses: actions/upload-artifact@v1
        with:
          name: reports
          path: build/reports

  sonarqube:
    name: SonarQube Check
    needs: tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Download test results
      uses: actions/download-artifact@v1
      with:
        name: reports
        path: build/reports
    - name: Sonarqube Check
      run: ./gradlew sonarqube -x test -x detekt
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
