name: CI Build

on:
  push:
    branches-ignore:
      - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Create Snapshot
        if: ${{ github.ref != 'master' }}
        run: echo ::set-env name=VERSION::$(./gradlew derive --preRelease='SNAPSHOT-'${GITHUB_REF##*/} -i --rerun-tasks | grep 'NEXT_VERSION:==' | sed 's/^.*NEXT_VERSION:==//g')
      - name: Create Release
        if: ${{ github.ref == 'master' }}
        run: echo "::set-output name=VERSION::$(./gradlew derive -i --rerun-tasks | grep 'NEXT_VERSION:==' | sed 's/^.*NEXT_VERSION:==//g')"
      - name: print variable
        run: echo ${{ env.VERSION }}
